tabPanel(title = "Insulin sensitivity",
         titlePanel("Boxplot for gene expression of different HOMA"),
         sidebarLayout(position = "left",
                       sidebarPanel = sidebarPanel(helpText("Create boxplot for gene expressions of different HOMA groups"), # nolint
                                                   pickerInput(inputId = "cohort_box_HOMA",
                                                               label = "Choose a cohort",
                                                               choices = list(subcutaneous=c("DEOSH"="DEOSHeset_Baseline", "DiOGenes1"="GSE141221_diogenes1", "DiOGenes2"="GSE95640_diogenes2", "EMIF"="EMIFeset_sc", "Krieg et al."="Krieg_et_al_sc", "Keller et al. sc"="Keller_et_al_sc", "PO"="POeset_Baseline", "RIKEN"="RIKENeset", "SOWOT"="SOWOTeset", "METSIM 770"="METSIM_770eset", "METSIM 434"="METSIM_434eset", "METSIM 200"="METSIM_200eset"),
                                                                              omental=c("EMIF"="EMIFeset_om", "Krieg et al."="Krieg_et_al_om", "Keller et al."="Keller_et_al_om")
                                                                              # epiploic=c("Krieg et al."="Krieg_et_al_ep"),
                                                                              # `mesenteric duodenum`=c("Krieg et al."="Krieg_et_al_md")
                                                               ),
                                                               selected = NA,
                                                               width = "300px",
                                                               options = list(size = 10, `live-search` = TRUE),
                                                               choicesOpt = list(subtext = c("sc","sc","sc","sc","sc","sc","sc","sc","sc","sc","om"))),
                                                   textAreaInput(inputId = "gene_HOMA",
                                                                 label = "Input gene name",
                                                                 value = "LEP",
                                                                 width = "300px",
                                                                 height = "50px",
                                                                 placeholder = "Only 1 gene"),
                                                   textAreaInput(inputId = "quantile_HOMA",
                                                                 label = "Input quantile",
                                                                 value = "2",
                                                                 width = "300px",
                                                                 height = "50px",
                                                                 placeholder = "Only 1 value"),
                                                   prettyRadioButtons(inputId = "statistical_test_cor_HOMA", 
                                                                      label = "Statistical test", 
                                                                      selected = "t.test", 
                                                                      choices = c("t-Test" = "t.test", "Wilcoxon Test" = "wilcox.test"), 
                                                                      inline = TRUE),
                                                   actionBttn(inputId = "SearchButton_box_HOMA",
                                                              label = "Search",
                                                              style = "simple",
                                                              color = "primary",
                                                              size = "sm"),
                                                   width = 3),
                       mainPanel = mainPanel(fluidRow(column(12, uiOutput("ui_boxplot_HOMA"))))
         )
)