tabPanel(title = "Scatter plot",
         titlePanel("Scatter plot for gene expression and clinical measures"),
         sidebarLayout(position = "left", 
                       sidebarPanel = sidebarPanel(helpText("Create Scatter plot with correlation between gene expression and clinical measure"), # nolint
                                                   pickerInput(inputId = "cohort_sp",
                                                               label = "Choose a cohort",
                                                               choices = list(subcutaneous=c("DEOSH"="DEOSHeset_Baseline", "DiOGenes1"="GSE141221_diogenes1", "DiOGenes2"="GSE95640_diogenes2", "EMIF"="EMIFeset_sc", "Krieg et al."="Krieg_et_al_sc", "Keller et al. sc"="Keller_et_al_sc", "PO"="POeset_Baseline", "RIKEN"="RIKENeset", "SOWOT"="SOWOTeset", "METSIM 770"="METSIM_770eset", "METSIM 434"="METSIM_434eset", "METSIM 200"="METSIM_200eset"),
                                                                              omental=c("EMIF"="EMIFeset_om", "Krieg et al."="Krieg_et_al_om", "Keller et al."="Keller_et_al_om")
                                                                              # epiploic=c("Krieg et al."="Krieg_et_al_ep"),
                                                                              # `mesenteric duodenum`=c("Krieg et al."="Krieg_et_al_md")
                                                               ), 
                                                               selected = "RIKENeset",
                                                               width = "300px",
                                                               options = list(size = 10, `live-search` = TRUE),
                                                               choicesOpt = list(subtext = c("sc","sc","sc","sc","sc","sc","sc","sc","sc","sc","sc","sc","om","om","om"))),
                                                   textAreaInput(inputId = "gene_sp", 
                                                                 label = "Input list of genes", 
                                                                 value = "", 
                                                                 width = "300px", 
                                                                 height = "300px", 
                                                                 placeholder = "A least 2 genes. Input empty will visualize the top 20 positive and negative correlated genes (no-adjustment mode) or the first 30 genes (adjustment mode)"), # nolint
                                                   pickerInput(inputId = "clinical_measure_sp",
                                                               label = "Clinical measure",
                                                               choices = clinical_measure_vector,
                                                               width = "300px",
                                                               options = list(size = 10,`live-search` = TRUE,`actions-box` = TRUE),
                                                               multiple = FALSE),
                                                   pickerInput(inputId = "clinical_measure_adjust_sp",
                                                               label = "Adjustment",
                                                               choices = NA,
                                                               width = "300px",
                                                               options = list(size = 10,`live-search` = TRUE,`actions-box` = TRUE),
                                                               multiple = TRUE),
                                                   # prettyCheckboxGroup(inputId = "clinical_measure_sp", 
                                                   #                     label = "Clinical measures", 
                                                   #                     choices = clinical_measure_vector,
                                                   #                     # selected = c("BMI","HOMA"),
                                                   #                     width = "300px",
                                                   #                     inline = T),
                                                   # materialSwitch(inputId = "select_all_sp", label = "Select all", right = TRUE, value = F),
                                                   prettyRadioButtons(inputId = "correlation_method_sp", 
                                                                      label = "Correlation method", 
                                                                      selected = "pearson", 
                                                                      choices = c("Pearson" = "pearson", "Spearman" = "spearman"), 
                                                                      inline = TRUE),
                                                   sliderTextInput(inputId = "correlation_cutoff_sp",
                                                                   label = "Correlation cut-off",
                                                                   choices = seq(0,1,0.01),
                                                                   width = "300px",
                                                                   grid = TRUE),
                                                   # sliderInput(inputId = 'Id098',
                                                   #             label = 'Correlation cut-off',
                                                   #             min = 0, 
                                                   #             max = 1, 
                                                   #             value = 0.05, 
                                                   #             step = 0.02),
                                                   actionBttn(inputId = "SearchButton_sp", 
                                                              label = "Search", 
                                                              style = "simple",
                                                              color = "primary",
                                                              size = "sm"),
                                                   width = 3),
                       mainPanel = mainPanel(fluidRow(column(12, uiOutput("ui_sp"))))
                       ) # sidebarLayout
         ) # tabPanel