tabPanel(title = "Characterization", 
         # tags$head(
         #   tags$link(rel = "stylesheet", type = "text/css", href = "style_def.css")
         # ),
         
         titlePanel("in vitro data"),
         sidebarLayout(sidebarPanel(
           width = 2,
           fileInput("file1", "Choose CSV File",
                     multiple = FALSE,
                     accept = c("text/csv",
                                "text/comma-separated-values,text/plain",
                                ".csv")),
           tags$hr(),
           tags$style(type="text/css", "textarea {width:100%}"),
           tags$textarea(id = 'gene_id', label = "Input your genes of interest", placeholder = c("PPARG","\nADIPOQ"), rows = 8),
           br(),
           radioButtons(inputId = "mode", label = "data type", choiceNames = c("mean abundance", "normalized mean abundance"), 
                        choiceValues = c("raw","normalized"), selected = "normalized"),
           actionButton(inputId = "start", label = "Visualize!"),
           tags$br(),
           tags$hr(),
           tags$br(),
           "You can use default settings or customize visualizations below:",
           tags$br(),
           "Gradient colors (applies to heatmaps)",
           tags$br(),
           radioButtons(inputId="gradient_col", choiceNames =  c("Purple to green", "Red to Blue" , "Viridis" ), choiceValues = c("PRGn", "RdBu", "viridis"), selected = "PRGn", label = NULL),
           tags$br(),
           "Discrete colors (applies to line charts, etc.)",
           tags$br(),
           textInput(inputId="discrete_col", value="Dark2", label = "Type ColorBrewer2 palette, e.g., Dark2"),
           tags$a(href="https://colorbrewer2.org/", "ColorBrewer2"),
           tags$br(),
           "further things to be implemented later: clustering method for heatmaps"),
           
           mainPanel(
             width = 10,
             navlistPanel(
               widths = c(2,8),
               "Adipogenesis",
               #NIGA#############
               tabPanel("ADSCs",
                        tabsetPanel(
                          tabPanel("Line chart",
                                   br(),
                                   plotlyOutput(outputId = "linechart"), br(),
                                   downloadButton(outputId = "download_pdf1", label = "Download PDF"),
                                   downloadButton(outputId = "download_gg1", label = "Download ggplot2")), 
                          tabPanel("HeatMap",
                                   br(),
                                   plotOutput("heatmap", width="80%"),
                                   br(),
                                   downloadButton(outputId = "download_pdf2", label = "Download PDF"), 
                                   downloadButton(outputId = "download_gg2", label = "Download ggplot2")), 
                          tabPanel("Table",
                                   br(),
                                   DT::dataTableOutput(outputId = "DT_NIGA", width = "100%"),
                                   br()),
                          tabPanel("About",
                                   br(),
                                   p(style="text-align: justify;","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque arcu lacus, molestie id facilisis ut, porta et neque. Nullam id ultricies urna, quis pulvinar tellus. Duis dignissim purus et gravida aliquet. Curabitur vel sapien purus. Etiam nisi mi, cursus vel arcu id, lobortis faucibus lacus. Praesent mauris odio, vulputate eu sapien vitae, maximus mollis erat. Etiam at venenatis lorem, nec cursus tellus. Nulla rutrum consectetur iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras id lacus at dolor lacinia imperdiet eu quis nunc. Nunc nisi ex, tincidunt ut ultricies eget, porta sed libero.
                              Sed eget velit sed mauris eleifend euismod. Duis a risus ultrices, tristique eros sit amet, tempor sapien. Aliquam ut placerat erat, ut viverra tellus. Integer commodo placerat justo, dignissim viverra elit semper a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare commodo nisi, vitae facilisis nisi feugiat sed. Quisque imperdiet ultrices eleifend. Vivamus sed fringilla nibh, maximus ultricies erat. ")),
                          
                        ),
                        tags$br(),
                        tags$hr(),
                        "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                        br(),
                        "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers DRA000991, DRA002711, DRA002747, and DRA002748" 
               ),
               #SVF###############
               tabPanel("SVF", 
                        tabsetPanel(
                          tabPanel("Line chart",
                                   br(),
                                   plotlyOutput(outputId = "linechart2"), br(),
                                   downloadButton(outputId = "download_pdf3", label = "Download PDF"),
                                   downloadButton(outputId = "download_gg3", label = "Download ggplot2")), 
                          tabPanel("HeatMap",
                                   br(),
                                   plotOutput("heatmap2", width="80%"),
                                   br(),
                                   downloadButton(outputId = "download_pdf4", label = "Download PDF"),
                                   downloadButton(outputId = "download_gg4", label = "Download ggplot2")), 
                          tabPanel("Table",
                                   br(),
                                   DT::dataTableOutput(outputId = "DT_SVF", width = "100%"),
                                   br()),
                          tabPanel("About",
                                   br(),
                                   p(style="text-align: justify;","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque arcu lacus, molestie id facilisis ut, porta et neque. Nullam id ultricies urna, quis pulvinar tellus. Duis dignissim purus et gravida aliquet. Curabitur vel sapien purus. Etiam nisi mi, cursus vel arcu id, lobortis faucibus lacus. Praesent mauris odio, vulputate eu sapien vitae, maximus mollis erat. Etiam at venenatis lorem, nec cursus tellus. Nulla rutrum consectetur iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras id lacus at dolor lacinia imperdiet eu quis nunc. Nunc nisi ex, tincidunt ut ultricies eget, porta sed libero.
                              Sed eget velit sed mauris eleifend euismod. Duis a risus ultrices, tristique eros sit amet, tempor sapien. Aliquam ut placerat erat, ut viverra tellus. Integer commodo placerat justo, dignissim viverra elit semper a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare commodo nisi, vitae facilisis nisi feugiat sed. Quisque imperdiet ultrices eleifend. Vivamus sed fringilla nibh, maximus ultricies erat. ")),
                        ),
                        tags$br(),
                        tags$hr(),
                        "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                        br(),
                        "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers DRA000991, DRA002711, DRA002747, and DRA002748" 
               ),
               "Cell type characterization",
               tabPanel("FACS fractionation",
                        tabsetPanel(
                          tabPanel("Heat map",
                                   br(),
                                   plotOutput(outputId = "heatmap_novo"),
                                   br(),
                                   downloadButton(outputId = "download_pdf7", label = "Download PDF"), 
                                   downloadButton(outputId = "download_gg7", label = "Download ggplot2")), 
                          tabPanel("Table",
                                   br(),
                                   DT::dataTableOutput("table_novo")),
                          tabPanel("About",
                                   br(),
                                   p(style="text-align: justify;","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque arcu lacus, molestie id facilisis ut, porta et neque. Nullam id ultricies urna, quis pulvinar tellus. Duis dignissim purus et gravida aliquet. Curabitur vel sapien purus. Etiam nisi mi, cursus vel arcu id, lobortis faucibus lacus. Praesent mauris odio, vulputate eu sapien vitae, maximus mollis erat. Etiam at venenatis lorem, nec cursus tellus. Nulla rutrum consectetur iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras id lacus at dolor lacinia imperdiet eu quis nunc. Nunc nisi ex, tincidunt ut ultricies eget, porta sed libero.
                              Sed eget velit sed mauris eleifend euismod. Duis a risus ultrices, tristique eros sit amet, tempor sapien. Aliquam ut placerat erat, ut viverra tellus. Integer commodo placerat justo, dignissim viverra elit semper a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare commodo nisi, vitae facilisis nisi feugiat sed. Quisque imperdiet ultrices eleifend. Vivamus sed fringilla nibh, maximus ultricies erat. ")),
                        ),
                        tags$br(),
                        tags$hr(),
                        "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                        br(),
                        "Raw data for this data set can be downloaded from: "
               ),
               tabPanel("FANTOM5 comparison",
                        tabsetPanel(
                          tabPanel("Heat map",
                                   br(),
                                   plotOutput(outputId = "heatmap_fantom"),
                                   br(),
                                   downloadButton(outputId = "download_pdf8", label = "Download PDF"), 
                                   downloadButton(outputId = "download_gg8", label = "Download ggplot2")), 
                          tabPanel("Table",
                                   br(),
                                   DT::dataTableOutput("table_fantom")),
                          tabPanel("About",
                                   br(),
                                   p(style="text-align: justify;","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque arcu lacus, molestie id facilisis ut, porta et neque. Nullam id ultricies urna, quis pulvinar tellus. Duis dignissim purus et gravida aliquet. Curabitur vel sapien purus. Etiam nisi mi, cursus vel arcu id, lobortis faucibus lacus. Praesent mauris odio, vulputate eu sapien vitae, maximus mollis erat. Etiam at venenatis lorem, nec cursus tellus. Nulla rutrum consectetur iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras id lacus at dolor lacinia imperdiet eu quis nunc. Nunc nisi ex, tincidunt ut ultricies eget, porta sed libero.
                              Sed eget velit sed mauris eleifend euismod. Duis a risus ultrices, tristique eros sit amet, tempor sapien. Aliquam ut placerat erat, ut viverra tellus. Integer commodo placerat justo, dignissim viverra elit semper a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare commodo nisi, vitae facilisis nisi feugiat sed. Quisque imperdiet ultrices eleifend. Vivamus sed fringilla nibh, maximus ultricies erat. ")),
                        ),
                        tags$br(),
                        tags$hr(),
                        "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                        br(),
                        "Raw data for this data set can be downloaded from: "
               ),
             )
           )
         ),
         div(
           class = "footer",
           includeHTML("footer.html")
         )
         )
