tabPanel(title = "Heatmap",
         titlePanel("Heatmap for gene expression and clinical measures"),
         sidebarLayout(position = "left", 
                       sidebarPanel = sidebarPanel(helpText("Create heatmap with correlation between gene expression and clinical measures."), # nolint
                                                   pickerInput(inputId = "cohort_hm",
                                                               label = "Choose a cohort",
                                                               choices = list(subcutaneous=c("DEOSH"="DEOSHeset_Baseline", "DiOGenes1"="GSE141221_diogenes1", "DiOGenes2"="GSE95640_diogenes2", "EMIF"="EMIFeset_sc", "Krieg et al."="Krieg_et_al_sc", "Keller et al. sc"="Keller_et_al_sc", "PO"="POeset_Baseline", "RIKEN"="RIKENeset", "SOWOT"="SOWOTeset", "METSIM 770"="METSIM_770eset", "METSIM 434"="METSIM_434eset", "METSIM 200"="METSIM_200eset"),
                                                                              omental=c("EMIF"="EMIFeset_om", "Krieg et al."="Krieg_et_al_om", "Keller et al."="Keller_et_al_om")
                                                                              # epiploic=c("Krieg et al."="Krieg_et_al_ep"),
                                                                              # `mesenteric duodenum`=c("Krieg et al."="Krieg_et_al_md")
                                                               ), 
                                                               selected = "RIKENeset",
                                                               width = "300px",
                                                               options = list(size = 10, `live-search` = TRUE),
                                                               choicesOpt = list(subtext = c("sc","sc","sc","sc","sc","sc","sc","sc","sc","sc","sc","sc","om","om","om"))),
                                                   textAreaInput(inputId = "gene_hm", 
                                                                 label = "Input list of genes", 
                                                                 value = "", 
                                                                 width = "300px", 
                                                                 height = "300px", 
                                                                 placeholder = "A least 2 genes. Input empty will use the first 30 genes of the cohort"), # nolint
                                                   pickerInput(inputId = "clinical_measure_hm",
                                                               label = "Clinical measures",
                                                               choices = clinical_measure_vector,
                                                               width = "300px",
                                                               options = list(size = 10,`live-search` = TRUE,`actions-box` = TRUE),
                                                               multiple = TRUE),
                                                   pickerInput(inputId = "clinical_measure_adjust_hm",
                                                               label = "Adjustment",
                                                               choices = NA,
                                                               width = "300px",
                                                               options = list(size = 10,`live-search` = TRUE,`actions-box` = TRUE),
                                                               multiple = TRUE),
                                                   # prettyCheckboxGroup(inputId = "clinical_measure_hm", 
                                                   #                     label = "Clinical measures", 
                                                   #                     choices = clinical_measure_vector,
                                                   #                     # selected = c("BMI","HOMA"),
                                                   #                     width = "300px",
                                                   #                     inline = T),
                                                   # materialSwitch(inputId = "select_all_hm", label = "Select all", right = TRUE, value = F),
                                                   prettyRadioButtons(inputId = "correlation_method_hm", 
                                                                      label = "Correlation method", 
                                                                      selected = "pearson", 
                                                                      choices = c("Pearson" = "pearson", "Spearman" = "spearman"), 
                                                                      inline = TRUE),
                                                   actionBttn(inputId = "SearchButton_hm", 
                                                              label = "Search", 
                                                              style = "simple",
                                                              color = "primary",
                                                              size = "sm"),
                                                   width = 3),
                       mainPanel = mainPanel(fluidRow(column(12, uiOutput("ui_all_hm"))))
                       ) # sidebarLayout
         ) # tabPanel
