tabPanel(title = "Weight loss",
         titlePanel("Boxplot for weight loss data"),
         sidebarLayout(position = "left",
                       sidebarPanel = sidebarPanel(helpText("Create box plot about weight loss data."), # nolint
                                                   textAreaInput(inputId = "gene_wl", 
                                                                 label = "Input gene name", 
                                                                 value = "LEP", 
                                                                 width = "300px", 
                                                                 height = "50px", 
                                                                 placeholder = "Only 1 gene"),
                                                   "or",
                                                   pickerInput(inputId = "clinical_measure_wl", 
                                                               label = "Choose a Clinical measure", 
                                                               choices = clinical_measure_vector,
                                                               width = "300px"),
                                                   prettyRadioButtons(inputId = "statistical_test_wl", 
                                                                      label = "Statistical test", 
                                                                      selected = "t.test", 
                                                                      choices = c("t-Test" = "t.test", "Wilcoxon Test" = "wilcox.test"), 
                                                                      inline = TRUE),
                                                   actionBttn(inputId = "SearchButton_wl", 
                                                              label = "Search", 
                                                              style = "simple",
                                                              color = "primary",
                                                              size = "sm"),
                                                   width = 3),
                       mainPanel = mainPanel(fluidRow(column(12, uiOutput("ui_boxplot_wl"))))
         )
)
