tabPanel(title = "Spatial",
         titlePanel("Spatial transcriptomics visualization"),
         fluidRow(column(width = 12,
                         column(width = 3,
                                pickerInput(inputId = "Dataset_STx",
                                            label = "Dataset: ",
                                            width = "200px",
                                            choices = c("Jesper et al. baseline"="Jesper_et_al_baseline", "Jesper et al. insulin"="Jesper_et_al_insulin"),
                                            selected = "Jesper_et_al_baseline")),
                         column(width = 3,
                                selectizeInput(inputId = 'gene_for_featureplot_STx',
                                               label = 'Gene: ',
                                               choices = NULL,
                                               selected = "ACAP3",
                                               width = "200px",
                                               # inline = TRUE,
                                               multiple = FALSE)),
                         column(width = 6,
                                pickerInput(inputId = "Slide_STx",
                                            label = "Slide: ",
                                            width = "200px",
                                            choices = NA,
                                            selected = NULL))
                         ), # column
                  column(width = 12,
                         column(width = 6,
                                tabsetPanel(id = "inTabset",
                                            tabPanel(title = "DimPlot",
                                                     column(12,uiOutput("ui_DimPlot_STx"))),
                                            tabPanel(title = "FeaturePlot", 
                                                     column(12,uiOutput("ui_FeaturePlot_STx"))),
                                            tabPanel(title = "Violin Plot",
                                                     column(12,uiOutput("ui_ViolinPlot_STx"))),
                                            tabPanel(title = "Marker",
                                                     column(12,uiOutput("ui_DT_STx")))
                                            )),
                         column(width = 6,
                                tabsetPanel(id = "inTabset",
                                            tabPanel(title = "SpatialDimPlot",
                                                     column(12,uiOutput("ui_SpatialDimPlot_STx"))),
                                            tabPanel(title = "SpatialFeaturePlot", 
                                                     column(12,uiOutput("ui_SpatialFeaturePlot_STx")))
                                            ))
                         ) # column
                  ) # fluidRow
         ) # tabPanel
