tabPanel(title = "Single Cell",
         titlePanel("single-cell visualization"),
         fluidRow(column(width = 12,
                         column(width = 3,
                                pickerInput(inputId = "Depots",
                                            label = "Depots: ",
                                            width = "200px",
                                            choices = c("All"="META_all", "Subcutaneous WAT"="META_all_sc", "Omental WAT"="META_all_om", "Perivascular WAT"="META_all_pvat"),
                                            selected = "META_all")),
                         column(width = 3,
                                selectizeInput(inputId = 'gene_for_featureplot',
                                               label = 'Gene: ',
                                               choices = NULL,
                                               selected = "ACAP3",
                                               width = "200px",
                                               # inline = TRUE,
                                               multiple = FALSE)),
                         # column(width = 3,
                         #        pickerInput(inputId = 'gene_for_featureplot',
                         #                    label = 'Gene: ',
                         #                    choices = NULL,
                         #                    selected = "ACAP3",
                         #                    width = "200px",
                         #                    # inline = TRUE,
                         #                    options = list(size = 10, `live-search` = TRUE),
                         #                    multiple = FALSE)),
                         column(width = 6,
                                pickerInput(inputId = "Subcluster",
                                            label = "Subcluster: ",
                                            width = "200px",
                                            choices = c("Lymphoid"="Lymphoid", "Myeloid"="Myeloid", "FAPs"="FAPs", "Vascular"="Vascular", "B cell" = "B"),
                                            selected = "Lymphoid"))
                         ), # column
                  column(width = 12,
                         column(width = 6,
                                tabsetPanel(id = "inTabset",
                                            tabPanel(title = "DimPlot",
                                                     column(12,uiOutput("ui_DimPlot_low"))),
                                            tabPanel(title = "FeaturePlot", 
                                                     column(12,uiOutput("ui_FeaturePlot_low"))),
                                            tabPanel(title = "Violin Plot",
                                                     column(12,uiOutput("ui_ViolinPlot_low"))),
                                            tabPanel(title = "Marker",
                                                     column(12,uiOutput("ui_DT_low"))))),
                         column(width = 6,
                                tabsetPanel(id = "inTabset",
                                            tabPanel(title = "DimPlot",
                                                     column(12,uiOutput("ui_DimPlot_high"))),
                                            tabPanel(title = "FeaturePlot", 
                                                     column(12,uiOutput("ui_FeaturePlot_high"))),
                                            tabPanel(title = "Violin Plot",
                                                     column(12,uiOutput("ui_ViolinPlot_high"))),
                                            tabPanel(title = "Marker",
                                                     column(12,uiOutput("ui_DT_high")))))
                         ) # column
                  ) # fluidRow
         ) # tabPanel
