library(shiny)
library(plotly)
library(shinyjs)
library(shinydashboard)
library(fresh)
library(shinyWidgets)
library(DT)

shinyUI(fluidPage(
  # useShinyjs(),
  tags$head(
    tags$script(src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/4.3.1/iframeResizer.contentWindow.min.js"),
    tags$link(rel = "stylesheet", type = "text/css", href = "style_def.css")
  ),
  # use_googlefont("Red Hat Display"),
  use_theme(create_theme(
    theme = "default",
    bs_vars_font(
      family_sans_serif = "'Red Hat Display', cursive"
    )
  )),
  tags$head(
    tags$style('
      .col-sm-3 { padding-left: 0px; padding-right: 15px; }
      .col-sm-9 { padding-left: 15px; padding-right: 0px; }
    ')
  ),
  
  sidebarLayout(
    div(class="sidebar",
        sidebarPanel(
          width=3,
          div(id="side-tab",
              tabsetPanel(
                tabPanel(title = "Input",     
                         br(),
                         div("Fill in your genes here:", class="highlight"),
                         br(),
                         tags$textarea(id = 'gene_id', label = "Input your genes of interest", placeholder = c("PPARG","\nADIPOQ"), rows = 8),
                         tags$hr(),
                         br(),
                         conditionalPanel(
                           condition = "input.perturbation === 'ko'",
                           pickerInput(inputId= "ko_gene", label="Select knock out/ knock down cell line", choices = ko_inputs, multiple=FALSE),
                         ),
                         conditionalPanel(
                           condition = "input.perturbation === 'tnf'",
                           pickerInput(inputId= "cell_line", label="Select cell line", choices = c("hMADS","SGBS"), multiple=FALSE),
                         ),
                         conditionalPanel(
                           condition = "input.perturbation === 'insulin'",
                           pickerInput(inputId= "cell_line2", label="Select in vivo or cell line", choices = c("in vivo","SGBS"), multiple=FALSE),
                         ),
                         conditionalPanel(
                           condition = "input.perturbation === 'inflamedAT'",
                           pickerInput(inputId = "inflamedAT_compare", label = "Select a comparison",
                                       choices = c("24h Treatment vs Control","48h Treatment vs Control", "All Treatment vs Control", "Treatment 24h vs 48h"))
                         ),
                         br(),
                         div("Select data type", class="highlight"),
                         
                         br(),
                         radioButtons(inputId = "mode", label = NULL, choiceNames = c("mean abundance", "normalized mean abundance"), 
                                      choiceValues = c("raw","normalized"), selected = "normalized"),
                         actionButton(inputId = "start", "Visualize!"),
                         tags$br()),
                tabPanel("Customization",
                         tags$br(),
                         div("You can use default settings or customize visualizations below:"),
                         tags$br(),
                         div("Gradient colors", class="highlight"),
                         div("applies to heatmaps"),
                         tags$br(),
                         radioButtons(inputId="gradient_col", choiceNames =  c("Default", "Purple to green", "Red to Blue" , "Viridis" ), choiceValues = c("default", "PRGn", "RdBu", "viridis"), selected = "default", label = NULL),
                         tags$br(),
                         div("Discrete colors",class="highlight"),
                         div("applies to line and bar charts"),
                         tags$br(),
                         radioButtons(inputId="discrete_col_sel", choiceNames =  c("Default", "Colorbrewer 2"), choiceValues = c("default_2", "CB2"), selected = "default_2", label = NULL),
                         div("if you selected ColorBrewer 2, please select a colorscheme below"),
                         selectInput(inputId= "discrete_col", label=NULL, choices = c("Accent","Dark2","Paired","Pastel1","Pastel2","Set1","Set2","Set3","Spectral",
                                                                                      "RdYlGn","RdYlBu","RdGy","RdBu","PuOr","PRGn","PiYG","BrBG"), selected = "Dark2"),
                         div("See", a(href="https://colorbrewer2.org/", "ColorBrewer2"), "for more"),
                         tags$br(),
                         div("Clustering method for heatmaps", class="highlight"),
                         tags$br(),
                         selectInput(inputId= "cluster_method", label=NULL, choices = c("ward.D","ward.D2","single","complete","average","mcquitty","median","centroid"), selected = "ward.D")
                )
              )))),
    div(class="main-content",
        mainPanel(
          width=9,
          navbarPage("Perturbation", id ="perturbation",
                     navbarMenu("Cell stress",
                                tabPanel("Hypoxia", value="hypoxia",
                                         includeHTML("htmls/description_hypoxia.html"), 
                                         tabsetPanel(
                                           
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_hyp"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_hyp1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_hyp1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_hyp"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_hyp2", label = "Download PDF", class = "butt"), 
                                                    downloadButton(outputId = "download_gg_hyp2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_hyp", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_hypoxia.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_hypoxia.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_hypoxia.html") 
                                ),
                                tabPanel("TNF", value="tnf",
                                         includeHTML("htmls/description_tnf.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_tnf"), br(),
                                                    downloadButton(outputId = "download_pdf_tnf1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download__tnf1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_tnf"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_tnf2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download__tnf2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_tnf", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_tnf.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_tnf.html")
                                           )),
                                         tags$br(),
                                         tags$hr(), 
                                         includeHTML("htmls/reference_tnf.html") 
                                ),
                                tabPanel("IL6", value="il6",
                                         includeHTML("htmls/description_il6.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_il6"), br(),
                                                    downloadButton(outputId = "download_pdf_il61", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_il61", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_il6"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_il62", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_il62", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_il6", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_il6.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_il6.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_il6.html") 
                                ),
                                tabPanel("TGFB1", value="tgfb1",
                                         includeHTML("htmls/description_tgfb.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_tgf"), br(),
                                                    downloadButton(outputId = "download_pdf_tgf1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_tgf1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_tgf"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_tgf2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_tgf2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_tgf", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_tgfb.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_tgfb.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_tgfb.html") 
                                ),
                                tabPanel("inflamed AT", value = "inflamedAT",
                                         includeHTML("htmls/description_inflat.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_inflAT"), br(),
                                                    downloadButton(outputId = "download_pdf_inflAT1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_inflAT1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_inflAT"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_inflAT2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_inflAT2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_inflAT", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_inflat.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_inflat.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_inflat.html") 
                                )
                     ),
                     navbarMenu("Hormonal",
                                tabPanel("Insulin", value = "insulin",
                                         includeHTML("htmls/description_insulin.html"),  
                                         
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_ins"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_ins1", label = "Download PDF", class = "butt"), 
                                                    downloadButton(outputId = "download_gg_ins1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput("dt_ins")),
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_ins"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_ins2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_ins2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_insulin.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_insulin.html"))),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_insulin.html")
                                ),
                                tabPanel("IGF1", value="igf1",
                                         includeHTML("htmls/description_igf.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_igf"), br(),
                                                    downloadButton(outputId = "download_pdf_igf1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_igf1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_igf"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_igf2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_igf2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_igf", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_igf.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_igf.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_igf.html")
                                ),
                                tabPanel("Adiponectin", value = "adipo",
                                         includeHTML("htmls/description_adipo.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_adipo"), br(),
                                                    downloadButton(outputId = "download_pdf_adipo1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_adipo1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_adipo"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_adipo2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_adipo2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_adipo", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_adipo.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_adipo.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_adipo.html")
                                ),
                                tabPanel("Leptin" , value = "leptin",
                                         includeHTML("htmls/description_leptin.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_lep"), br(),
                                                    downloadButton(outputId = "download_pdf_lep1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_lep1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_lep"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_lep2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_lep2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_lep", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_leptin.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_leptin.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_leptin.html")
                                )
                     ),
                     navbarMenu("Pharmacologic",
                                tabPanel("Rosiglitazone", value="rosi",
                                         includeHTML("htmls/description_rosi.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_rosi"), br(),
                                                    downloadButton(outputId = "download_pdf_rosi1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_rosi1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_rosi"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_rosi2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_rosi2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_rosi", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_rosi.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_rosi.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_rosi.html")
                                ),
                                tabPanel("Dexamethasone", value = "dexa",
                                         includeHTML("htmls/description_dexa.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_dexa"), br(),
                                                    downloadButton(outputId = "download_pdf_dexa1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_dexa1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_dexa"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_dexa2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_dexa2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_dexa", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_dexa.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_dexa.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_dexa.html")
                                ),
                                tabPanel("Isoprenaline", value = "iso",
                                         includeHTML("htmls/description_iso.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_iso"), br(),
                                                    downloadButton(outputId = "download_pdf_iso1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_iso1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_iso"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_iso2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_iso2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_iso", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_iso.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_iso.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_iso.html")
                                ),
                                tabPanel("IBMX", value = "ibmx",
                                         includeHTML("htmls/description_ibmx.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_ibmx"), br(),
                                                    downloadButton(outputId = "download_pdf_ibmx1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_ibmx1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_ibmx"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_ibmx2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_ibmx2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_ibmx", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_ibmx.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_ibmx.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_ibmx.html")
                                ),
                                tabPanel("Metformin", value = "metformin",
                                         includeHTML("htmls/description_met.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_met"), br(),
                                                    downloadButton(outputId = "download_pdf_met1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_met1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_met"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_met2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_met2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_met", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_met.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_met.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_met.html")
                                ),
                                tabPanel("Atorvastatin", value = "atorva",
                                         includeHTML("htmls/description_atorva.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_atorva"), br(),
                                                    downloadButton(outputId = "download_pdf_atorva1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_atorva1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_atorva"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_atorva2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_atorva2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_atorva", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_atorva.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_atorva.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_atorva.html")
                                ),
                                tabPanel("SB203580", value ="SB203580",
                                         includeHTML("htmls/description_sb.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_sb"), br(),
                                                    downloadButton(outputId = "download_pdf_sb1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_sb1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_sb"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_sb2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_sb2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_sb", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_sb.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_sb.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_sb.html")
                                ),
                                tabPanel("SP600125" , value = "SP600125",
                                         includeHTML("htmls/description_sp.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_sp"), br(),
                                                    downloadButton(outputId = "download_pdf_sp1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_sp1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_sp"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_sp2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_sp2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_sp", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_sp.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_sp.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_sp.html")
                                ),
                                tabPanel("UO126", value="UO126",
                                         includeHTML("htmls/description_uo.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_uo"), br(),
                                                    downloadButton(outputId = "download_pdf_uo1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_uo1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_uo"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_uo2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_uo2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_uo", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_uo.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_uo.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_uo.html")
                                )
                     ),
                     
                     navbarMenu("Metabolic",
                                tabPanel("Glucose",value="glucose",
                                         includeHTML("htmls/description_glucose.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_glucose"), br(),
                                                    downloadButton(outputId = "download_pdf_glucose1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_glucose1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_glucose"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_glucose2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_glucose2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_glucose", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_glucose.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_glucose.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_glucose.html")
                                ),
                                tabPanel("Retinoic Acid", value = "retinoic",
                                         includeHTML("htmls/description_ra.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_ra"), br(),
                                                    downloadButton(outputId = "download_pdf_ra1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_ra1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_ra"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_ra2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_ra2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_ra", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_ra.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_ra.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_insulin.html")
                                ),
                                tabPanel("Lauroyl L Carnithine", value = "lauroyl",
                                         includeHTML("htmls/description_lauro.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_lauro"), br(),
                                                    downloadButton(outputId = "download_pdf_lauro1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_lauro1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_lauro"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_lauro2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_lauro2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_lauro", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_lauro.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_lauro.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_lauro.html")
                                ),
                                tabPanel("Decanoyl L Carnithine", value = "decanoyl",
                                         includeHTML("htmls/description_decano.html"),
                                         tabsetPanel(
                                           tabPanel("Heatmap",
                                                    br(),
                                                    plotOutput(outputId = "heatmap_decano"), br(),
                                                    downloadButton(outputId = "download_pdf_decano1", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_decano1", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Volcano",
                                                    br(),
                                                    shinycustomloader::withLoader(plotOutput(outputId = "volcano_decano"), type="html", loader="dnaspin"),
                                                    br(),
                                                    downloadButton(outputId = "download_pdf_decano2", label = "Download PDF", class = "butt"),
                                                    downloadButton(outputId = "download_gg_decano2", label = "Download ggplot2", class = "butt"),
                                                    tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                           tabPanel("Table",
                                                    br(),
                                                    DT::dataTableOutput(outputId = "dt_decano", width = "100%"),
                                                    br()),
                                           tabPanel("Details",
                                                    includeHTML("htmls/details_decano.html")
                                           ),
                                           tabPanel("Interpretation",
                                                    includeHTML("htmls/interpretation_decano.html")
                                           )),
                                         tags$br(),
                                         tags$hr(),
                                         includeHTML("htmls/reference_decano.html")
                                )),
                     navbarMenu("Genetic", 
                                tabPanel("knock out/down",value="ko",
                                         uiOutput("knockdowns")       
                                ),
                                tabPanel("miRNAs", value = "miRNA")
                     ),
          )))
    
    
  )
)
)#end shiny UI

