library(shiny)
library(plotly)
library(shinyjs)
library(shinydashboard)
library(fresh)
library(shinyWidgets)
library(DT)

shinyUI(fluidPage(
  useShinyjs(),
  tags$head(
    tags$link(rel = "stylesheet", type = "text/css", href = "style_def.css")
  ),
  use_googlefont("Red Hat Display"),
  use_theme(create_theme(
    theme = "default",
    bs_vars_font(
      family_sans_serif = "'Red Hat Display', cursive"
    )
    )),
  div(class="container" ,
  br(), 
  br(),
  #titlePanel("Module III: Characterization"),
  sidebarLayout(
    div(class="sidebar",
    sidebarPanel(
      width=3,div(id="side-tab",
      tabsetPanel(
          tabPanel("Input",     
      br(),
      div("Fill in your genes here:", class="highlight"),
      br(),
      tags$textarea(id = 'gene_id', label = "Input your genes of interest", placeholder = c("PPARG","\nADIPOQ"), rows = 8),
      tags$hr(),
      br(),
        conditionalPanel(
          condition = "input.perturbation === 'ko'",
          pickerInput(inputId= "ko_gene", label="Select knock out/ knock down cell line", choices = ko_inputs, multiple=FALSE),
        ),
      conditionalPanel(
        condition = "input.perturbation === 'insulin' || input.perturbation === 'tnf'",
        pickerInput(inputId= "cell_line", label="Select cell line", choices = c("hMADS","SGBS"), multiple=FALSE),
      ),
      conditionalPanel(
        condition = "input.perturbation === 'inflamedAT'",
        pickerInput(inputId = "inflamedAT_compare", label = "Select a comparison",
                    choices = c("24h Treatment vs Control","48h Treatment vs Control", "All Treatment vs Control", "Treatment 24h vs 48h"))
      ),
      br(),
      div("Select data type", class="highlight"),

     br(),
      radioButtons(inputId = "mode", label = NULL, choiceNames = c("mean abundance", "normalized mean abundance"), 
                 choiceValues = c("raw","normalized"), selected = "normalized"),
      actionButton(inputId = "start", "Visualize!"),
      tags$br()),
      tabPanel("Customization",
      tags$br(),
      div("You can use default settings or customize visualizations below:"),
      tags$br(),
      div("Gradient colors", class="highlight"),
      div("applies to heatmaps"),
      tags$br(),
      radioButtons(inputId="gradient_col", choiceNames =  c("Default", "Purple to green", "Red to Blue" , "Viridis" ), choiceValues = c("default", "PRGn", "RdBu", "viridis"), selected = "default", label = NULL),
      tags$br(),
      div("Discrete colors",class="highlight"),
      div("applies to line and bar charts"),
      tags$br(),
      radioButtons(inputId="discrete_col_sel", choiceNames =  c("Default", "Colorbrewer 2"), choiceValues = c("default_2", "CB2"), selected = "default_2", label = NULL),
      div("if you selected ColorBrewer 2, please select a colorscheme below"),
      selectInput(inputId= "discrete_col", label=NULL, choices = c("Accent","Dark2","Paired","Pastel1","Pastel2","Set1","Set2","Set3","Spectral",
                                                                   "RdYlGn","RdYlBu","RdGy","RdBu","PuOr","PRGn","PiYG","BrBG"), selected = "Dark2"),
      div("See", a(href="https://colorbrewer2.org/", "ColorBrewer2"), "for more"),
      tags$br(),
      div("Clustering method for heatmaps", class="highlight"),
      tags$br(),
      selectInput(inputId= "cluster_method", label=NULL, choices = c("ward.D","ward.D2","single","complete","average","mcquitty","median","centroid"), selected = "ward.D")
      )
      )))),
    div(class="main-content",
    mainPanel(
      navbarPage("Perturbation", id ="perturbation",
                 navbarMenu("Cell stress",
                            tabPanel("Hypoxia", value="hypoxia",
                                     div("adipose tissue derived stem cells", class="highlight"),
                                     includeHTML("htmls/description_ADSCs.html"), 
                                     # div(actionButton("toggle_table3", HTML("&dtrif;"), style="font-size:16px; padding: 0px;"), "Show available output options", class="highlight"),
                                     # div(id= "gene_table3", style = "display:none;",includeHTML("htmls/outputs_hADSC.html")),
                                     tabsetPanel(
                                       
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_hyp"),
                                                br(),
                                                downloadButton(outputId = "download_pdf1", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg1", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_hyp"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf2", label = "Download PDF", class = "butt"), 
                                                downloadButton(outputId = "download_gg2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_hyp", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_ADSCs.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_ADSCs.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022") ,  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748"), 
                            ),
                            tabPanel("TNF", value="tnf",
                                     div("Ex vivo stroma vascular fraction", class="highlight"),
                                     includeHTML("htmls/description_SVF.html"),
                                     # div(actionButton("toggle_table4", HTML("&dtrif;"), style="font-size:16px; padding: 0px;"), "Show available output options", class="highlight"),
                                     # div(id = "gene_table4", style = "display:none;",includeHTML("htmls/outputs_SVF.html")),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_tnf"), br(),
                                                downloadButton(outputId = "download_pdf3", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg3", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_tnf"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf4", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg4", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_tnf", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748") 
                            ),
                            tabPanel("IL6", value="il6",
                                     div("IL6 treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_il6"), br(),
                                                downloadButton(outputId = "download_pdf_il6", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_il6", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_il6"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_il62", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_il62", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_il6", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                                     ),
                            tabPanel("TGFB1", value="tgfb1",
                                     div("TGFB1 treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_tgf"), br(),
                                                downloadButton(outputId = "download_pdf_tgf", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_tgf", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_tgf"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_tgf2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_tgf2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_tgf", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                                     ),
                            tabPanel("inflamed AT", value = "inflamedAT",
                                     div("SGBS cells treated with conditioned media from inflamed WAT", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_inflAT"), br(),
                                                downloadButton(outputId = "download_pdf_inflAT", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_inflAT", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_inflAT"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_inflAT2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_inflAT2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_inflAT", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            )
                            ),
                 navbarMenu("Hormonal",
                            tabPanel("Insulin",value="insulin",
                          includeHTML("htmls/description_tissue.html"),
                          # div(actionButton("toggle_table", HTML("&dtrif;"), style="font-size:16px; padding: 0px;"), "Show available output options", class="highlight"),
                          # div(id= "gene_table", style = "display:none;",includeHTML("htmls/outputs_tissue.html")),   
                                     br(),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_ins"),
                                                br(),
                                                downloadButton(outputId = "download_pdf8", label = "Download PDF", class = "butt"), 
                                                downloadButton(outputId = "download_gg8", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput("dt_ins")),
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_ins"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf9", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg9", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_tissue.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_tissue.html"))),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded fromthe DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748"), 
                                     
                            ),
                          tabPanel("IGF1", value="igf1",
                                   div("IGF1 treatment of SGBS cells", class="highlight"),
                                   #includeHTML("htmls/description_SVF.html"),
                                   tabsetPanel(
                                     tabPanel("Heatmap",
                                              br(),
                                              plotOutput(outputId = "heatmap_igf"), br(),
                                              downloadButton(outputId = "download_pdf_igf", label = "Download PDF", class = "butt"),
                                              downloadButton(outputId = "download_gg_igf", label = "Download ggplot2", class = "butt"),
                                              tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                     tabPanel("Volcano",
                                              br(),
                                              shinycustomloader::withLoader(plotOutput(outputId = "volcano_igf"), type="html", loader="dnaspin"),
                                              br(),
                                              downloadButton(outputId = "download_pdf_igf2", label = "Download PDF", class = "butt"),
                                              downloadButton(outputId = "download_gg_igf2", label = "Download ggplot2", class = "butt"),
                                              tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                     tabPanel("Table",
                                              br(),
                                              DT::dataTableOutput(outputId = "dt_igf", width = "100%"),
                                              br()),
                                     tabPanel("Details",
                                              includeHTML("htmls/details_SVF.html")
                                     ),
                                     tabPanel("Interpretation",
                                              includeHTML("htmls/interpretation_SVF.html")
                                     )),
                                   tags$br(),
                                   tags$hr(),
                                   "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                   br(),
                                   "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                          ),
                          tabPanel("Adiponectin", value = "adipo",
                                   div("Adiponectin treatment of SGBS cells", class="highlight"),
                                   #includeHTML("htmls/description_SVF.html"),
                                   tabsetPanel(
                                     tabPanel("Heatmap",
                                              br(),
                                              plotOutput(outputId = "heatmap_adipo"), br(),
                                              downloadButton(outputId = "download_pdf_adipo", label = "Download PDF", class = "butt"),
                                              downloadButton(outputId = "download_gg_adipo", label = "Download ggplot2", class = "butt"),
                                              tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                     tabPanel("Volcano",
                                              br(),
                                              shinycustomloader::withLoader(plotOutput(outputId = "volcano_adipo"), type="html", loader="dnaspin"),
                                              br(),
                                              downloadButton(outputId = "download_pdf_adipo2", label = "Download PDF", class = "butt"),
                                              downloadButton(outputId = "download_gg_adipo2", label = "Download ggplot2", class = "butt"),
                                              tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                     tabPanel("Table",
                                              br(),
                                              DT::dataTableOutput(outputId = "dt_adipo", width = "100%"),
                                              br()),
                                     tabPanel("Details",
                                              includeHTML("htmls/details_SVF.html")
                                     ),
                                     tabPanel("Interpretation",
                                              includeHTML("htmls/interpretation_SVF.html")
                                     )),
                                   tags$br(),
                                   tags$hr(),
                                   "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                   br(),
                                   "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                          ),
                          tabPanel("Leptin" , value = "leptin",
                                   div("Leptin treatment of SGBS cells", class="highlight"),
                                   #includeHTML("htmls/description_SVF.html"),
                                   tabsetPanel(
                                     tabPanel("Heatmap",
                                              br(),
                                              plotOutput(outputId = "heatmap_lep"), br(),
                                              downloadButton(outputId = "download_pdf_lep", label = "Download PDF", class = "butt"),
                                              downloadButton(outputId = "download_gg_lep", label = "Download ggplot2", class = "butt"),
                                              tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                     tabPanel("Volcano",
                                              br(),
                                              shinycustomloader::withLoader(plotOutput(outputId = "volcano_lep"), type="html", loader="dnaspin"),
                                              br(),
                                              downloadButton(outputId = "download_pdf_lep2", label = "Download PDF", class = "butt"),
                                              downloadButton(outputId = "download_gg_lep2", label = "Download ggplot2", class = "butt"),
                                              tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                     tabPanel("Table",
                                              br(),
                                              DT::dataTableOutput(outputId = "dt_lep", width = "100%"),
                                              br()),
                                     tabPanel("Details",
                                              includeHTML("htmls/details_SVF.html")
                                     ),
                                     tabPanel("Interpretation",
                                              includeHTML("htmls/interpretation_SVF.html")
                                     )),
                                   tags$br(),
                                   tags$hr(),
                                   "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                   br(),
                                   "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                          )
                          ),
                 navbarMenu("Pharmacologic",
                            tabPanel("Rosiglitazone", value="rosi",
                                     div("Rosiglitazone treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_rosi"), br(),
                                                downloadButton(outputId = "download_pdf_rosi", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_rosi", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_rosi"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_rosi2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_rosi2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_rosi", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            ),
                            tabPanel("Dexamethasone", value = "dexa",
                                     div("Dexamethasone treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_dexa"), br(),
                                                downloadButton(outputId = "download_pdf_dexa", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_dexa", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_dexa"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_dexa2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_dexa2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_dexa", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            ),
                            tabPanel("Isoprenaline", value = "iso",
                                     div("Isoprenaline treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_iso"), br(),
                                                downloadButton(outputId = "download_pdf_iso", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_iso", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_iso"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_iso2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_iso2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_iso", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            ),
                            tabPanel("IBMX", value = "ibmx",
                                     div("IBMX treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_ibmx"), br(),
                                                downloadButton(outputId = "download_pdf_ibmx", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_ibmx", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_ibmx"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_ibmx2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_ibmx2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_ibmx", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            ),
                            tabPanel("Metformin", value = "metformin",
                                     div("Metformin treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_met"), br(),
                                                downloadButton(outputId = "download_pdf_met", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_met", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_met"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_met2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_met2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_met", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            ),
                            tabPanel("Atorvastatin", value = "atorva",
                                     div("Atorvastatin treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_atorva"), br(),
                                                downloadButton(outputId = "download_pdf_atorva", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_atorva", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_atorva"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_atorva2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_atorva2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_atorva", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            ),
                            tabPanel("SB203580", value ="SB203580",
                                     div("SB203580 treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_sb"), br(),
                                                downloadButton(outputId = "download_pdf_sb", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_sb", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_sb"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_sb2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_sb2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_sb", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            ),
                            tabPanel("SP600125" , value = "SP600125",
                                     div("SP600125 treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_sp"), br(),
                                                downloadButton(outputId = "download_pdf_sp", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_sp", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_sp"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_sp2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_sp2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_sp", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            ),
                            tabPanel("UO126", value="UO126",
                                     div("UO126 treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_uo"), br(),
                                                downloadButton(outputId = "download_pdf_uo", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_uo", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_uo"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_uo2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_uo2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_uo", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            )
                            ),
                
                 navbarMenu("Metabolic",
                            tabPanel("Glucose",value="glucose",
                                     div("Glucose treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_glucose"), br(),
                                                downloadButton(outputId = "download_pdf_glucose", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_glucose", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_glucose"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_glucose2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_glucose2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_glucose", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            ),
                            tabPanel("Retinoic Acid", value = "retinoic",
                                     div("Retinoic Acid treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_ra"), br(),
                                                downloadButton(outputId = "download_pdf_ra", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_ra", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_ra"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_ra2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_ra2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_ra", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            ),
                            tabPanel("Lauroyl L Carnithine", value = "lauroyl",
                                     div("Lauroyl L Carnithine treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_lauro"), br(),
                                                downloadButton(outputId = "download_pdf_lauro", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_lauro", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_lauro"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_lauro2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_lauro2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_lauro", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            ),
                            tabPanel("Decanoyl L Carnithine", value = "decanoyl",
                                     div("Decanoyl L Carnithine treatment of SGBS cells", class="highlight"),
                                     #includeHTML("htmls/description_SVF.html"),
                                     tabsetPanel(
                                       tabPanel("Heatmap",
                                                br(),
                                                plotOutput(outputId = "heatmap_decano"), br(),
                                                downloadButton(outputId = "download_pdf_decano", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_decano", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Volcano",
                                                br(),
                                                shinycustomloader::withLoader(plotOutput(outputId = "volcano_decano"), type="html", loader="dnaspin"),
                                                br(),
                                                downloadButton(outputId = "download_pdf_decano2", label = "Download PDF", class = "butt"),
                                                downloadButton(outputId = "download_gg_decano2", label = "Download ggplot2", class = "butt"),
                                                tags$head(tags$style(".butt {background-color:  #1a4659;} .butt{color: #E2C744;} .butt{border-color: #E2C744;}"))), 
                                       tabPanel("Table",
                                                br(),
                                                DT::dataTableOutput(outputId = "dt_decano", width = "100%"),
                                                br()),
                                       tabPanel("Details",
                                                includeHTML("htmls/details_SVF.html")
                                       ),
                                       tabPanel("Interpretation",
                                                includeHTML("htmls/interpretation_SVF.html")
                                       )),
                                     tags$br(),
                                     tags$hr(),
                                     "If you want to use this figure in your publication, please cite:", tags$a(href="https://pubmed.ncbi.nlm.nih.gov/27803022/", "Ehrlund et al.; PMID: 27803022"),  "(data) and Zhong et al. (portal).",
                                     br(),
                                     "Raw data for this data set can be downloaded from the DNA Data Bank of Japan under accession numbers", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA000991", "DRA000991"),",", tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002711", "DRA002711"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002747", "DRA002747"),",",tags$a(href="https://ddbj.nig.ac.jp/resource/sra-submission/DRA002748", "DRA002748")
                            )),
                 navbarMenu("Genetic", 
                            tabPanel("knock out/down",value="ko",
                            uiOutput("knockdowns")       
                              ),
                            tabPanel("miRNAs", value = "miRNA")
                            ),
)))
  
   
)
)#end div class container
)
)#end shiny UI
